# docker-compose build
# docker-compose run --rm app go run db/migrate.go up

version: '3'

services:
  app:
    build: ./containers/app
    working_dir: "/go/src/github.com/stobita/bike_api/"
    volumes:
      - '.:/go/src/github.com/stobita/bike_api/'
    ports:
      - '8085:8085'
    command: 'realize start --run --no-config'
    environment:
      PORT: 8085
      BIKE_DB_USER: gouser
      BIKE_DB_PASS: gouser
      BIKE_DB_HOST: db
      BIKE_DB_NAME: bike_api
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: bike_api
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gouser
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '4306:3306'
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - s3-data:/export
    entrypoint: sh
    command: -c 'mkdir -p /export/bike-api-sample && /usr/bin/minio server /export'
    environment:
      MINIO_ACCESS_KEY: sample_access_key
      MINIO_SECRET_KEY: sample_secret_key
      MINIO_REGION: sample_region
volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
