FROM golang:1.11

RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/pressly/goose
RUN go get github.com/gin-gonic/gin
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/go-xorm/xorm
RUN go get golang.org/x/crypto/bcrypt
RUN go get github.com/codegangsta/gin
RUN go get github.com/olahol/go-imageupload
RUN go get github.com/aws/aws-sdk-go
